---
name: Build, Test, and Lint (C++)

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clean PlatformIO Cache
      - name: Clean PlatformIO Cache
        run: platformio run --target clean || true

      # Step 2: Cache PlatformIO Dependencies
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      # Step 3: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 4: Set up Python (for PlatformIO)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 5: Install PlatformIO and Clang-Tidy
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          sudo apt-get update && sudo apt-get install -y clang-tidy

      # Step 6: Verify Directory Structure
      - name: Verify Directory Structure
        run: ls -R

      # Step 7: Initialize Submodules
      - name: Initialize Submodules
        run: git submodule update --init --recursive

      # Step 8: Build Firmware
      - name: Build Firmware
        run: platformio run -v

      # Step 9: Upload Firmware (if applicable)
      - name: Upload Firmware
        run: platformio run --target upload
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}

      # Step 10: Lint C++ Code with Clang-Tidy
      - name: Lint C++ Code
        run: clang-tidy $(find src lib -name "*.cpp") -- -std=c++17

      # Step 11: Debug Include Paths
      - name: Debug Include Paths
        run: |
          echo "Inspecting include paths..."
          platformio run --target clean
          platformio run -v || true

      # Step 12: Debugging Logs
      - name: Output Environment Details
        run: |
          echo "Python Version:"
          python --version
          echo "Installed Packages:"
          python -m pip list
