name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clean PlatformIO Cache
    - name: Clean PlatformIO Cache
      run: platformio run --target clean || true

    # Step 2: Cache PlatformIO Dependencies
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-

    # Step 3: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 4: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 5: Install PlatformIO
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    # Step 6: List Directory Structure
    - name: Verify Directory Structure
      run: ls -R

    # Step 7: Initialize Submodules
    - name: Initialize Submodules
      run: git submodule update --init --recursive

    # Step 8: Build Firmware (Verbose)
    - name: Build Firmware
      run: platformio run -v

    # Step 9: Upload Firmware
    - name: Upload Firmware (if applicable)
      run: platformio run --target upload
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}

    # Step 10: Debug Missing Files
    - name: Debug Include Paths
      run: |
        echo "Inspecting include paths..."
        platformio run --target clean
        platformio run -v || true
