name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install PlatformIO
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    # Step 4: Verify Directory Structure
    - name: List directory structure
      run: ls -R

    # Step 5: Initialize Submodules
    - name: Initialize submodules
      run: git submodule update --init --recursive

    # Step 6: Build Firmware (Verbose Mode)
    - name: Build firmware (verbose)
      run: platformio run -v

    # Step 7: Upload firmware (if applicable)
    - name: Upload firmware (if applicable)
      run: platformio run --target upload
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}